### ISSUE TITLE
Create add*State options in createState page

### ISSUE THREAD

**Issue by albertocuestacanada** [HQ20/insig#13]
Please rename to addState page.

**Comment by albertocuestacanada** [comment]
Would you mind renaming these?

Add root state -> Create Asset
Add state -> Add State
Handover state -> Handover Asset
Part Of state -> Compose Asset
View state -> View State

It's funny that three actions in /states actually make more sense expressed in asset terms, we might do some changes in the future.

**Comment by obernardovieira** [comment]
can we close?

**Comment by albertocuestacanada** [comment]
Please capitalize these in the same way and close:

![image](https://user-images.githubusercontent.com/38806121/58678791-eb53a900-8358-11e9-80bc-5fea190e08b4.png)
