### ISSUE TITLE
Rename item for asset throughout the code

### ISSUE THREAD

**Issue by albertocuestacanada** [HQ20/insig#21]
Asset is more precise and matches the supply chain vocabulary. That I know in the contracts there are item, Item and ITEM capitalizations, in singular and plural.

**Comment by albertocuestacanada** [comment]
You missed these ones :)

![image](https://user-images.githubusercontent.com/38806121/58547309-0a3e2800-81ff-11e9-839a-3349829b387e.png)

**Comment by obernardovieira** [comment]
CASE SENSITIVE PROBLEMS! :joy: Solved! Thanks.
