### ISSUE TITLE
View Role

### ISSUE THREAD

**Issue by albertocuestacanada** [HQ20/insig#22]
The roles page should have an option to enter a role id and recover the role info (description and admin role).

We can't easily show the bearers anymore since they are stored in a mapping now :P

**Comment by obernardovieira** [comment]
valid?

**Comment by albertocuestacanada** [comment]
Almost, when vieweing each role we see an admin role, which also should be a link:

![image](https://user-images.githubusercontent.com/38806121/58678689-8a2bd580-8358-11e9-85db-77f181db6454.png)

**Comment by obernardovieira** [comment]
All the roles are listed below, always. I think its redundant.
