### ISSUE TITLE
View State

### ISSUE THREAD

**Issue by albertocuestacanada** [HQ20/insig#23]
There should be an option in the states page to enter a state id and recover all the info from that state (creator, action, item/asset, precedents, partOf, operator, owner).

This code will be reused, as this is the data that should be shown when clicking on a state from the graph.

**Comment by albertocuestacanada** [comment]
Viewing state data should be accessible through REST as http://insiġ,io/states/<state_id>

**Comment by albertocuestacanada** [comment]
The data shown when viewing a state should be linked to the other pages:

creator - Not linked
action - link to /actions/<action>
asset - link to /assets/<asset> (renamed from item)
partOf - link to /assets/<partOf> (renamed from item)
owner - link to /roles/<owner>
owner - link to /roles/<operator>

**Comment by albertocuestacanada** [comment]
I can't see the links :/

**Comment by obernardovieira** [comment]
Sorry, didn't get what was requested!

**Comment by albertocuestacanada** [comment]
Ah, so this was the REST interface for.

With a link I mean that if we are viewing a state, and the state says that its operator role is 1 you should be able to click that 1 and it would take you to Roles.View.1

Similarly for all other fields everywhere. You are viewing a state that refers to Asset 123, click the 123, it takes you to Assets.View.123 (not implemented, so for now it can take you to Asset.LastState)

**Comment by obernardovieira** [comment]
related to #24, please review it

**Comment by albertocuestacanada** [comment]
Done, thank you
