### ISSUE TITLE
Items

### ISSUE THREAD

**Issue by albertocuestacanada** [HQ20/insig#24]
Create an assets page. For now it has a single action which is "Last State" which returns the last known state for that asset. (Renamed from item).

In the future other options will be:
getPartOf
getComposite
getOperator
getOwner

**Comment by albertocuestacanada** [comment]
The state returned should be a link, that takes us to states/<state id> (REST for the view action on the states page.)

**Comment by albertocuestacanada** [comment]
Viewing an item data should be what happens when opening http://insiġ,io/items/<item_id> in a browser

**Comment by albertocuestacanada** [comment]
Working, good job.

**Comment by obernardovieira** [comment]
Great. Thanks.

> The state returned should be a link, that takes us to states/ (REST for the view action on the states page.)

This was not implemented. Should be? I think it's related to https://github.com/HQ20/insig/issues/23#issuecomment-494393259

**Comment by albertocuestacanada** [comment]
No, REST interfaces were not implemented.You can leave them for now unless you find them a fun project.

I'm undecided whether a REST interface should return a human-readable page, or a JSON.

**Comment by obernardovieira** [comment]
please review it.

**Comment by albertocuestacanada** [comment]
Awesome, really nice, thanks.
