### ISSUE TITLE
Token.view

### ISSUE THREAD

**Issue by albertocuestacanada** [HQ20/insig#26]
Token.view should take an asset id and return:

Whether the token exists - Token.exists(asset id)
The token faceValue - Token.faceValues[asset id] - This is the value entered in the Token.mint method.
The token accumulated revenue - Token.revenues[asset id] - This will be zero until we implement the Token.pay method.

**Comment by albertocuestacanada** [comment]
The token accumulated revenue doesn't show yet.

Token.revenues[asset id]

**Comment by obernardovieira** [comment]
Please, have a look now.

**Comment by albertocuestacanada** [comment]
Gorgeous, thanks.
