### ISSUE TITLE
Token.burn

### ISSUE THREAD

**Issue by albertocuestacanada** [HQ20/insig#27]
Tokens can be burned, only the asset id should be required.

**Comment by albertocuestacanada** [comment]
Basic functionality works.

It should show a message if the token cannot be burned. The UI just didn't do anything when I tried to burn a token I didn't own, and I should have been told.

It is funny that it didn't even ask me to confirm the transaction, how did the frontend know that I didn't own the asset for which I was minting the token.

**Comment by albertocuestacanada** [comment]
An error occurred! :+1: 

Now it is much clearer, thanks.

**Comment by obernardovieira** [comment]
Since we have error messages, should I catch it and print?

**Comment by albertocuestacanada** [comment]
Yes please.

**Comment by obernardovieira** [comment]
Done! :+1:
