### ISSUE TITLE
Token.pay

### ISSUE THREAD

**Issue by albertocuestacanada** [HQ20/insig#28]
The pay section doesn't use real ERC20 tokens, it just takes an amount from the user interface and an asset id.

The results of the pay function can be seen by using Token.view, the payments will be in Token.revenues[asset id]

**Comment by albertocuestacanada** [comment]
Blocked because I can't see the accumulated revenue in Token.View :)

**Comment by obernardovieira** [comment]
Added.

**Comment by albertocuestacanada** [comment]
Working like a charm
